server:
  port: 8081
spring:
  application:
    name: taskapp-api-gateway
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 985494108713-d6c2p24i17tou59sltk3a8df1lm7iicj.apps.googleusercontent.com
            client-secret: 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

logging:
    file: 
      name: logs/apigateway.log
    level:
        org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: "prometheus, health"

#opentracing:
#  jaeger:
#    log-spans: false
#    http-sender:
#       url: ${JAEGER_HTTP_URL:http://localhost:14268/api/traces}

api.destinations:
    taskapiurl: 
      getall: http://localhost:8080/yuma/task/getall
      get: http://localhost:8080/yuma/task
      delete: http://localhost:8080/yuma/task
      change: http://localhost:8080/yuma/task
      add: http://localhost:8080/yuma/task
    dnmonster:
      get: http://localhost:8082/monster

