server:
  port: 8081
spring:
  application:
    name: taskapp-api-gateway
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${SECRET_KEY}

logging:
    file: 
      name: logs/apigateway.log
    level:
        org.springframework.web: INFO
        com.amazonaws.xray: INFO

management:
  endpoints:
    web:
      exposure:
        include: "prometheus, health"

#opentracing:
#  jaeger:
#    log-spans: false
#    http-sender:
#       url: ${JAEGER_HTTP_URL:http://localhost:14268/api/traces}

api.destinations:
    taskapiurl: 
      getall: http://taskapp-read-service:5001/yuma/task/getall
      get: http://taskapp-read-service:5001/yuma/task
      delete: http://taskapp-cud-service:5002/yuma/task
      change: http://taskapp-cud-service:5002/yuma/task
      add: http://taskapp-cud-service:5002/yuma/task
    dnmonster:
      get: http://dnmonster-service:6001/monster